config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#index'
  resources :bank_accounts, only: [:index, :show]
end

app/models/account_transaction.rb
class AccountTransaction < ApplicationRecord
  belongs_to :bank_account
  TRANSACTION_TYPES = ["withdraw", "deposit"]
  validates :bank_account, presence: true
  validates :amount, presence: true, numericality: true
  validates :transaction_type, presence: true, inclusion: {in: TRANSACTION_TYPES}
  validates :transaction_number, presence: true, uniqueness: true


before_validation :load_defaults

def load_defaults
    if self.new_record?
        self.transaction_number = SecureRandom.uuid
    end
end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bank_account.rb
class BankAccount < ApplicationRecord
  belongs_to :client
  validates :client, presence: true
  validates :account_number, presence: true, uniqueness: true
  validates :balance, presence: true, numericality: true
  
  before_validation :load_defaults
  has_many :account_transactions
  
  def load_defaults
      if self.new_record?
          self.balance = 0.00
      end
  end
  
  def to_s
      account_number
  end
end

app/models/client.rb
class Client < ApplicationRecord
    validates :first_name, presence: true
    validates :last_name, presence: true
    validates :middle_name, presence: true
    validates :client_number, presence: true, uniqueness: true
    
    before_save :format_name
    
    has_many :bank_accounts
    
    def format_name
        self.first_name = self.first_name.upcase
        self.last_name = self.last_name.upcase
        self.middle_name = self.middle_name.upcase
    end
    
    def to_s
        last_name+" "+first_name+" "+middle_name
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/bank_accounts_controller.rb
class BankAccountsController < ApplicationController
    def index
        @bank_accounts = BankAccount.all
    end
    
    def show
        @bank_account = BankAccount.find(params[:id])
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def no_of_accounts
        BankAccount.count
    end
    
    def no_of_clients
        Client.count
    end
    
   
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/bank_accounts/index.html.erb
<h1>Bank Accounts</h1>
<table class="table table-bordered">
    <thead>
        <tr>
            <th>Account Number</th>
            <th>Balance</th>
            <th>Actions</th>
        </tr>
    </thead>
    
    <tbody>
        <% @bank_accounts.each do |bank_account| %>
        <tr>
           <td><%= bank_account.account_number %></td>
           <td><%= number_to_currency(bank_account.balance, unit: "P") %></td>
           <td><%= link_to 'show', bank_account_path(bank_account.id) %></td>
        </tr>
        <% end %>
    </tbody>
</table>

app/views/bank_accounts/show.html.erb
<h1>Account Number: <%= @bank_account.account_number %></h1>
<small><%=@bank_account.client %></small><br/>

<%= button_tag :new_transaction,  id: "btn-new-transaction", class: "btn btn-primary" %>

<table class = "table table-bordered">
  <thead>
     <tr>
       <th>Date of transaction</th>
       <th>Transaction_type</th>
       <th>Amount</th>
     </tr>
  </thead
  
  <tbody>
    <% @bank_account.account_transactions.each do |t| %>
        <tr>
          <td><%=t.created_at %></td>
          <td><%=t.transaction_type %></td>
          <td><%=number_to_currency(t.amount, unit: "P") %></td>
        </tr>
    <% end %>
    <tr>
      <th></th>
      <th>Balance</th>
      <th><%= number_to_currency(@bank_account.balance, unit: "P") %></th>
    </tr>
  </tbody>
</table>

<div class="modal fade modal-fade", id: "modal-transaction">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
        </button>
        <h4 class="modal-title"> New Transaction </h4>
      </div>
      <div class="modal-body">
        <div class="row"></div>
        <div class="col-md-6"></div>
        <label>Amount</label>
        <%= text_field_tag :amount,0.00, id: "input-amount", class: "form-control" %>
        <div class="col-md-6"></div>
        <label>Transaction_type</label>
        <%=select_tag :transaction_type, options_for_select(AccountTransaction::TRANSACTION_TYPES), id: "select-transaction-type", class: "form-control"%>
      </div>
      <div class="modal-footer">
        <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
        <button<div id="btn-save"></div> class="btn btn-primary" {type="button">} Save</button>
      </div>
    </div>
  </div>
</div>






<%= javascript_include_tag "bank_accounts/show" %>
<script>
$(document).ready(function(){
  show.init();
});
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bank</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
     <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

<!-- jQuery library -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

<!-- Latest compiled JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script> 
  </head>

  <body>
    <div class='container'>
    <%= yield %>
    </div>
  </body>
</html>

app/views/pages/index.html.erb
<div class = 'container'>
    <div class = 'row'>
        <div class = 'col-md-12'>
            <h1>My Bank</h1>
            <h2>No of Accounts: <%=no_of_accounts %></h2>
            <h2>No of Clients: <%=no_of_clients %></h2>
            <%= link_to 'Bank Accounts', bank_accounts_path %>
        </div>
    </div>
</div>